### ISSUE TITLE
Proposal: Add type constants

### ISSUE THREAD

**Issue by flimzy** [gopherjs/jsbuiltin#10]
To avoid bare strings all over my code, I'm thinking it might be nice to define constants for the names of JS data types.  Thus:

    if jsbuiltin.TypeOf(foo) == "undefined" {

becomes:

    if jsbuiltin.TypeOf(foo) == jsbuiltin.TypeUndefined {

etc.

1. Does this seem like a good idea?
2. Is this the right place to put such constants?
3. How should they be named?  (`TypeFoo` vs `Foo` vs `FooType` vs ??)

**Comment by shurcooL** [comment]
My thoughts as someone who wouldn't use this, in case it's at all helpful. Ignore if not.

This sounds reasonable to me, and this package is where'd I'd expect it to go.

> To avoid bare strings all over my code

It's hard for me to comment beyond that because I do not have any such bare strings in my code (I write primarily Go), so I wouldn't have a use for this.

**Comment by shurcooL** [comment]
That said, `js` package already has support for detecting undefined, is there a reason not to use that? Am I missing something?

https://godoc.org/github.com/gopherjs/gopherjs/js#Undefined

```Go
if foo == is.Undefined {
```

**Comment by flimzy** [comment]
Using the `js` package to detect Undefined is certainly better.  But of course that's not the only use for type checking, so I'm still of the opinion that the addition might make sense.
